# -*- coding: utf-8 -*-
"""프원실_과제07_02_리스트_202210981_김은주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CChDTalKzTb-IQCwbBQdxFL6v0SwxmCv
"""

#과제(2). 1-n까지 리스트를 돌려주는 함수를 만드시오. 함수는 get_range_list(n)
def get_range_list(n):
    return list(range(1, n + 1))

def main():
    n = int(input("숫자를 입력하세요: "))
    result = get_range_list(n)
    print(result)

if __name__ == "__main__":
    main()