# -*- coding: utf-8 -*-
"""프원실_과제07_04_사전형_202210981_김은주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CChDTalKzTb-IQCwbBQdxFL6v0SwxmCv
"""

#과제(4). 딸기 300g, 한라봉 150g 섭취하였을 때, 입력자료를 사전형으로 전달하면, 총 칼로리를 계산하는 함수를 만드시오. fruits={“딸기”: 300, “한라봉”: 150}, fruits_calorie_dic={"한라봉":50, "딸기": 34, "바나나": 77}.
#과제 #06-01 활용. 함수명은 total_calorie(fruits, fruits_calorie_dic)

def total_calorie(fruits, fruits_calorie_dic):
  total_calorie = 0
  for fruit in fruits:
    total_calorie += fruits[fruit] * fruits_calorie_dic[fruit]
  return total_calorie

def main():
  fruits = {"딸기": 300, "한라봉": 150}
  fruits_calorie_dic = {"한라봉": 50, "딸기": 34, "바나나": 77}
  result = total_calorie(fruits, fruits_calorie_dic)
  print(result)

if __name__ == "__main__":
    main()