# -*- coding: utf-8 -*-
"""프원실_과제07_03_년도_202210981_김은주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CChDTalKzTb-IQCwbBQdxFL6v0SwxmCv
"""

#과제(3). 연도(y)를 주면, 윤년인지(True) 아닌지를(False) 알려주는 is_leap_year(y) 함수를 만드시오. 단 윤년의 조건은 주어진 조건으로 구현하시오. 4로 나누었을 때 나누어 떨어지면 윤년. 4로 나누어떨어지더라도, 100으로 나누어 떨어진다면, 윤년 아님.
def is_leap_year(y):
  if y % 4 == 0 and not y % 100 == 0 :
    return True
  else:
    return False

def main():
    y = int(input("연도를 입력하세요: "))
    result = is_leap_year(y)
    print(result)

if __name__ == "__main__":
    main()